apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: multicluster-observability-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: multicluster-observability-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: multicluster-observability-operator-system
