resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- config.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- acm-optimization-overview-dash.yaml
- acm-clusters-overview-dash.yaml
- k8s-mixin-dashboards.yaml