apiVersion: v1
data:
  grafana.ini: W2F1dGhdDQpkaXNhYmxlX2xvZ2luX2Zvcm0gPSB0cnVlDQpkaXNhYmxlX3NpZ25vdXRfbWVudSA9IHRydWUNCg0KW2F1dGguYW5vbnltb3VzXQ0KZW5hYmxlZCA9IGZhbHNlDQoNCltwYXRoc10NCmRhdGEgPSAvdmFyL2xpYi9ncmFmYW5hDQpsb2dzID0gL3Zhci9saWIvZ3JhZmFuYS9sb2dzDQpwbHVnaW5zID0gL3Zhci9saWIvZ3JhZmFuYS9wbHVnaW5zDQpwcm92aXNpb25pbmcgPSAvZXRjL2dyYWZhbmEvcHJvdmlzaW9uaW5nDQoNCltzZWN1cml0eV0NCmFkbWluX3VzZXIgPSBhZG1pbg0KYWRtaW5fcGFzc3dvcmQgPSBzZWNyZXQNCg0KW3NlcnZlcl0NCmh0dHBfcG9ydCA9IDMwMDENCnJvb3RfdXJsID0gJShwcm90b2NvbClzOi8vJShkb21haW4pcy9ncmFmYW5hLw0KZG9tYWluID0gbG9jYWxob3N0DQoNClt1c2Vyc10NCnZpZXdlcnNfY2FuX2VkaXQgPSB0cnVlDQo=
kind: Secret
metadata:
  name: grafana-config
  namespace: open-cluster-management
type: Opaque
