apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: multiclustermonitorings.monitoring.open-cluster-management.io
spec:
  group: monitoring.open-cluster-management.io
  names:
    kind: MultiClusterMonitoring
    listKind: MultiClusterMonitoringList
    plural: multiclustermonitorings
    singular: multiclustermonitoring
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MultiClusterMonitoring is the Schema for the multiclustermonitorings
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MultiClusterMonitoringSpec defines the desired state of MultiClusterMonitoring
          properties:
            grafana:
              description: Spec of Grafana
              properties:
                enabled:
                  description: Enabled for enable grafana
                  type: boolean
              type: object
            imagePullPolicy:
              description: Pull policy of the MultiClusterMonitor images
              type: string
            imagePullSecret:
              description: Pull secret of the MultiClusterMonitor images
              type: string
            imageRepository:
              description: Repository of the MultiClusterMonitor images
              type: string
            imageTagSuffix:
              description: ImageTagSuffix of the MultiClusterMonitor images
              type: string
            nodeSelector:
              description: Spec of NodeSelector
              properties:
                customLabelSelector:
                  description: Spec of CustomLabelSelector
                  type: string
                customLabelValue:
                  description: Spec of CustomLabelValue
                  type: string
                os:
                  description: Spec of OS
                  type: string
              type: object
            observatorium:
              description: Spec of Observatorium
              properties:
                compactVolumeSize:
                  description: CompactVolumeSize for compact volume size (ex. 50Gi)
                  type: string
                enabled:
                  description: Enabled for enable observatorium
                  type: boolean
                receiversVolumeSize:
                  description: ReceiversVolumeSize for receivers volume size (ex.
                    50Gi)
                  type: string
                ruleVolumeSize:
                  description: RuleVolumeSize for rule volume size (ex. 50Gi)
                  type: string
                storageClass:
                  description: StorageClass for Observatorium component
                  type: string
                storeVolumeSize:
                  description: StoreVolumeSize for store volume size (ex. 50Gi)
                  type: string
              type: object
            version:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                Version of the MultiClusterMonitor'
              type: string
          required:
          - grafana
          - imagePullPolicy
          - imageRepository
          - imageTagSuffix
          - observatorium
          - version
          type: object
        status:
          description: MultiClusterMonitoringStatus defines the observed state of
            MultiClusterMonitoring
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
