apiVersion: monitoring.open-cluster-management.io/v1
kind: MultiClusterMonitoring
metadata:
  name: example-multiclustermonitoring
spec:
  storageClass: {{storageClass}}
  observatorium:
    enabled: true
    compactVolumeSize: 50Gi
    receiversVolumeSize: 50Gi
    ruleVolumeSize: 50Gi
    storeVolumeSize: 50Gi
  grafana:
    enabled: true

