apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: open-cluster-management-rule
spec:
  clusterSelector:
    matchExpressions:
      - {key: monitoring, operator: NotIn, values: [disabled]}