name: Update go module dependencies versions

# Set jobs to be configured and executed by schedule.
on:
  push: # Actions will be executed by pushing changes to the listed branches.
    branches:
      - 'main'
      - 'releases/**'
  schedule:
    - cron: '0 8 * * Tue' # Actions will be executed at 8am for every Tuesday.

# Set environment variables.
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup go for repository code
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17' # Go version should be 1.17 or higher.

      - name: Validate go version
        run: |
          echo "Using go version: $(go version)"

  update:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Verify outdated go modules versions
        run: |
          echo "Preparing to list go modules within current build"
          go list -u -m all

      - name: Update go modules to latest versions
        run: |
          echo "Preparing to update all go modules to latest versions"
          go get -u all
          go mod tidy

      - name: Validate package build properly
        run: |
          echo "Preparing to build package"
          go build ./...

  test:
    needs: [build, update]
    runs-on: ubuntu-latest
    steps:
      - name: Test repoisitory code after updating go module to the latest version
        run: | 
          echo "Preparing to run test repository code"
          go test ./...
