apiVersion: v1
data:
  k8s-slo.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 15,
      "iteration": 1629816479596,
      "links": [
        {
          "icon": "dashboard",
          "tags": [],
          "title": "Kubernetes / SLO / Cluster",
          "type": "link",
          "url": "./d/3TB9bRnnz/kubernetes-sli-cluster?orgId=1"
        }
      ],
      "panels": [
        {
          "collapsed": false,
          "datasource": null,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 28,
          "panels": [],
          "title": "SLO's Status",
          "type": "row"
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": null,
          "fieldConfig": {
            "defaults": {
              "color": {},
              "custom": {},
              "thresholds": {
                "mode": "absolute",
                "steps": []
              },
              "unit": "short"
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 12,
            "w": 24,
            "x": 0,
            "y": 1
          },
          "hiddenSeries": false,
          "id": 24,
          "interval": "5m",
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.4.2",
          "pointradius": 2,
          "points": true,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sli:apiserver_request_duration_seconds:filtered:trend:5m{slo=\"$slo\"}",
              "format": "time_series",
              "instant": false,
              "interval": "5m",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "$slo (All Clusters)",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "$$hashKey": "object:942",
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "$$hashKey": "object:943",
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "datasource": null,
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "left",
                "filterable": false
              },
              "mappings": [
                {
                  "from": "",
                  "id": 1,
                  "text": "-",
                  "to": "",
                  "type": 1,
                  "value": "null"
                }
              ],
              "noValue": "-",
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "percentunit"
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byName",
                  "options": "Cluster"
                },
                "properties": [
                  {
                    "id": "links",
                    "value": [
                      {
                        "title": "",
                        "url": "./d/3TB9bRnnz/kubernetes-slo-cluster?orgId=1&var-cluster=﻿${__data.fields.cluster}﻿&var-slo=${__data.fields.slo}"
                      }
                    ]
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 9,
            "w": 24,
            "x": 0,
            "y": 13
          },
          "id": 10,
          "interval": "5m",
          "options": {
            "showHeader": true
          },
          "pluginVersion": "7.4.2",
          "targets": [
            {
              "expr": "sli:apiserver_request_duration_seconds:trend:5m{slo=\"$slo\"}",
              "format": "table",
              "instant": false,
              "interval": "5m",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Status (All Clusters)",
          "transformations": [
            {
              "id": "merge",
              "options": {}
            },
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "Time": false,
                  "__name__": true
                },
                "indexByName": {
                  "Time": 0,
                  "Value": 4,
                  "__name__": 1,
                  "cluster": 2,
                  "slo": 3
                },
                "renameByName": {
                  "Value #A": "Status",
                  "Value #B": "Status",
                  "Value #C": "Status",
                  "cluster": "Cluster",
                  "slo": "Name",
                  "target": "Target",
                  "time": "Time"
                }
              }
            }
          ],
          "type": "table"
        },
        {
          "datasource": null,
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "continuous-RdYlGr"
              },
              "custom": {},
              "mappings": [
                {
                  "from": "",
                  "id": 1,
                  "text": "N/A",
                  "to": "",
                  "type": 1,
                  "value": "null"
                }
              ],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "percentunit"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 22
          },
          "id": 25,
          "interval": "5m",
          "options": {
            "colorMode": "value",
            "graphMode": "none",
            "justifyMode": "center",
            "orientation": "vertical",
            "reduceOptions": {
              "calcs": [
                "lastNotNull"
              ],
              "fields": "",
              "limit": 10,
              "values": false
            },
            "text": {},
            "textMode": "value_and_name"
          },
          "pluginVersion": "7.4.2",
          "targets": [
            {
              "expr": "sli:apiserver_request_duration_seconds:trend:5m{slo=\"$slo\"}",
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": "7d",
          "timeShift": null,
          "title": "Past 7 Days ",
          "transformations": [
            {
              "id": "labelsToFields",
              "options": {
                "valueLabel": "cluster"
              }
            },
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "Time": true
                },
                "indexByName": {},
                "renameByName": {}
              }
            }
          ],
          "type": "stat"
        },
        {
          "datasource": null,
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "continuous-RdYlGr"
              },
              "custom": {},
              "mappings": [
                {
                  "from": "",
                  "id": 1,
                  "text": "N/A",
                  "to": "",
                  "type": 1,
                  "value": "null"
                }
              ],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "percentunit"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 22
          },
          "id": 20,
          "interval": "5m",
          "options": {
            "colorMode": "value",
            "graphMode": "none",
            "justifyMode": "center",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": [
                "lastNotNull"
              ],
              "fields": "",
              "limit": 10,
              "values": false
            },
            "text": {},
            "textMode": "auto"
          },
          "pluginVersion": "7.4.2",
          "targets": [
            {
              "expr": "sli:apiserver_request_duration_seconds:trend:5m{slo=\"$slo\"}",
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": "30d",
          "timeShift": null,
          "title": "Past 30 Days",
          "transformations": [
            {
              "id": "labelsToFields",
              "options": {
                "valueLabel": "cluster"
              }
            }
          ],
          "type": "stat"
        },
        {
          "collapsed": true,
          "datasource": null,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 30
          },
          "id": 30,
          "panels": [],
          "repeat": null,
          "title": "Error Budget",
          "type": "row"
        },
        {
          "datasource": null,
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "continuous-RdYlGr"
              },
              "custom": {
                "align": null,
                "filterable": false
              },
              "mappings": [
                {
                  "from": "",
                  "id": 1,
                  "text": "N/A",
                  "to": "",
                  "type": 1,
                  "value": "null"
                }
              ],
              "thresholds": {
                "mode": "percentage",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 98
                  },
                  {
                    "color": "#EAB839",
                    "value": 99
                  }
                ]
              },
              "unit": "none"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 10,
            "w": 24,
            "x": 0,
            "y": 31
          },
          "id": 22,
          "interval": "5m",
          "options": {
            "showHeader": true
          },
          "pluginVersion": "7.4.2",
          "targets": [
            {
              "expr": "sli:apiserver_request_duration_seconds:filtered:trend:5m{slo=\"$slo\"}",
              "format": "table",
              "instant": false,
              "interval": "5m",
              "legendFormat": "",
              "refId": "A"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Remaining Budget (Currrent)",
          "transformations": [
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "Time": false,
                  "__name__": true
                },
                "indexByName": {},
                "renameByName": {}
              }
            },
            {
              "id": "groupBy",
              "options": {
                "fields": {
                  "Value": {
                    "aggregations": [],
                    "operation": "groupby"
                  },
                  "cluster": {
                    "aggregations": [],
                    "operation": "groupby"
                  }
                }
              }
            },
            {
              "id": "calculateField",
              "options": {
                "mode": "reduceRow",
                "reduce": {
                  "reducer": "count"
                }
              }
            }
          ],
          "type": "table"
        }
      ],
      "refresh": false,
      "schemaVersion": 27,
      "style": "dark",
      "tags": [
        "kubernetes-mixin",
        "SLO"
      ],
      "templating": {
        "list": [
          {
            "allValue": null,
            "current": {
              "selected": false,
              "text": "API Server Request Duration",
              "value": "API Server Request Duration"
            },
            "datasource": null,
            "definition": "label_values(slo)",
            "description": null,
            "error": null,
            "hide": 0,
            "includeAll": false,
            "label": "SLO",
            "multi": false,
            "name": "slo",
            "options": [],
            "query": {
              "query": "label_values(slo)",
              "refId": "StandardVariableQuery"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "tagValuesQuery": "",
            "tags": [],
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          }
        ]
      },
      "time": {
        "from": "now-5m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Kubernetes / SLO",
      "uid": "L8KmaR7nz",
      "version": 42
    }
kind: ConfigMap
metadata:
  name: grafana-dashboard-k8s-slo
  namespace: open-cluster-management-observability
  labels:
    general-folder: 'true'