name: Update package dependencies versions

# Set jobs to be configured and executed by schedule.
on:
  workflow_dispatch: # Workflow dispatch allows you to trigger the job manually
    environment:
      description: Environment to run build against
      type: environment
  push:
    branches:
      - 'main'
      - 'release-*'
  schedule:
    - cron: '0 8 * * 1-5' # Actions will be executed at 8am for every weekday.

# Set environment variables.
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup go for repository code
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17' # Go version should be 1.17 or higher.
          check-latest: true

      - name: Validate installed go version
        run: |
          echo "Using go version: $(go version)"

      - name: Verify outdated go modules versions
        continue-on-error: true # Continuing on error, we need to check for outdated modules, so it's okay for this step to fail.
        run: |
          echo "Preparing to list go modules within current build"
          go list -u -m all

      - name: Update go modules to latest versions
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: |
          echo "Preparing to update all go modules to latest versions"
          go get -u all
          go mod tidy

      - name: Validate package build properly
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: |
          echo "Preparing to build package"
          go build ./...

      - name: Create report to README
        run: |
          echo -e "\nGenerated auto rebuild: $(date +%d-%m-%y)" >> README.md
          git status

      - name: Create pull request for updated node modules versions
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: .
          body: >
            This PR is auto-generated by the Git action [go-package-update](https://github.com/stolostron/multicluster-observability-operator/blob/main/.github/workflows/go-package-update.yml).
          branch-suffix: short-commit-hash
          commit-message: 'Updated node module versions within the project'
          delete-branch: true
          labels: automated-pr
          reviewers: dislbenn
          signoff: true
          title: '[Automated PR] Updated go modules versions within the project'
          token: ${{ secrets.GITHUB_TOKEN }}
