name: Update go module dependencies versions

# Set jobs to be configured and executed by schedule.
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 8 * * Mon-Fri' # Actions will be executed at 8am for every weekday.

# Set environment variables.
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup go for repository code
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17' # Go version should be 1.17 or higher.

      - name: Check out branch for pull request
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b automated-branch-$(date +%S-%d-%m-%y)

      - name: Validate go version
        run: |
          echo "Using go version: $(go version)"

      - name: Verify outdated go modules versions
        continue-on-error: true # Continuing on error, we need to check for outdated modules, so it's okay for this step to fail.
        run: |
          echo "Preparing to list go modules within current build"
          go list -u -m all

      - name: Update go modules to latest versions
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: |
          echo "Preparing to update all go modules to latest versions"
          go get -u all
          go mod tidy

      - name: Validate package build properly
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: |
          echo "Preparing to build package"
          go build ./...

      - name: Test repository code after updating go module to the latest version
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: | 
          echo "Preparing to run test repository code"
          go test ./...

      - name: Create report to Readme
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: |
          echo -e "\nCreated automated PR: $(date +%S-%d-%m-%y)" >> Readme.md
          git status
          git add -A

      - name: Create pull request for updated node modules versions
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: .
          body: >
            This PR is auto-generated by the Git action [search-e2e-test](https://github.com/stolostron/multicluster-observability-operator/blob/main/.github/workflows/package-dependencies-update.yml).
          commit-message: 'Updated node module versions within the project'
          delete-branch: true
          signoff: true
          title: '[Automated PR] Updated node modules versions within the project'
          token: ${{ secrets.GITHUB_TOKEN }}
